apiVersion: apps/v1
kind: Deployment
metadata:
  name: shantanuk8api
spec:
  selector:
    matchLabels:
      app: shantanuk8api
  replicas: 1
  template:
    metadata:
      labels:
        app: shantanuk8api
    spec:
      containers:
      - name: shantanu-web-app
        image: kshantanu/shantanu-web-app
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: shantanu-web-api
spec:
  type: NodePort
  selector:
    app: shantanuk8api
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30011
    name: http
  - port: 443
    targetPort: 443
    nodePort: 30015
    name: https